apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-spar2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/exea-centrum/website-db-vault-kaf-redis-arg-kust-kyv-elk-apm-sprig-spar2.git
    targetRevision: HEAD
    directory:
      recurse: true
      include: "*.yaml"
      exclude: "kustomization.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: davtroelkjs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
