apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: davtroelkjs
  labels:
    app: spark
    component: worker
spec:
  replicas: 2  # Możesz zmienić liczbę workerów
  selector:
    matchLabels:
      app: spark
      component: worker
  template:
    metadata:
      labels:
        app: spark
        component: worker
    spec:
      containers:
      - name: spark-worker
        image: apache/spark:3.5.1
        command: 
        - "/opt/spark/sbin/start-worker.sh"
        args:
        - "spark://spark-master:7077"
        env:
        - name: SPARK_WORKER_CORES
          value: "2"
        - name: SPARK_WORKER_MEMORY
          value: "2g"
        - name: SPARK_WORKER_PORT
          value: "7078"
        - name: SPARK_WORKER_WEBUI_PORT
          value: "8081"
        - name: SPARK_LOCAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 7078
          name: worker
        - containerPort: 8081
          name: worker-webui
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          tcpSocket:
            port: 7078
          initialDelaySeconds: 30
          periodSeconds: 10